export default {
    KO : {
        LOGOUT : '로그아웃',
        search : '검색',
        apply : "적용",
        langKO : '국문',
        langEN : '영문',
        langCN : '중문',
        langJP : '일문',
        text : "텍스트",
        close : '닫기',
        save : '저장',
        cancel : '취소',
        totalCnt : '{{cnt}} 개',
        'design image' : '디자인 이미지',
        'my image' : '내이미지',
        mallCode : '상품코드',
        'Product Name' : '상품코드',
        'created date' : '생성날짜',
        render : '렌더',
        type : '구분',
        tag : '태그',
        category : '카테고리',
        "descending" : "내림차순",
        "ascending" : "오름차순",
        "block name" : '블럭명',
        "block type" : '블럭유형',
        saving : '저장중입니다.',
        searching : '검색중입니다',
        progressing : '진행중입니다.',
        saveFail : '저장실패',
        initComplete : "초기화 완료",
        magicWand : '누끼',
        initError : '초기화 실패',
        askConfirm : '검수 요청',
        cancelConfirm : '검수 취소',
        doneConfirm : '검수 완료',
        designer : '디자이너',
        qa : '검수자',

        htmlCoordinates : '영역크기&amp;좌표',
        htmlTransparency : '투명도(투명-불투명)',
        colorTransparency : '색상 및 투명도',
        htmlOriginalSize : '원본 크기',
        htmlMaskSize : '영역 크기',
        htmlImageCrop : '이미지 크롭',
        htmlDegree : '회전',
        htmlImageSizeManagement : '이미지 관리',
        htmlStyle : '스타일',
        htmlRequestRender : '렌더 요청',
        htmlChooseShop : '상점 선택',
        htmlSearchCondition : '검색조건',
        tagInputPlz : '태그를 입력해 주세요.',
        inputProductCode : '상품코드를 입력해주세요',
        searchResultEmpty : '검색 결과가 없습니다',
        autoMagicWandDone : '자동 누끼 이미지 변환 성공',
        servicePluginTimeoutError : '프로그램 오픈 타임아웃 발생 - 재실행 해주세요',
        servicePluginInstall : '누끼툴이 설치되어 있지 않습니다.',
        servicePluginInstall2 : '다운로드하여 설치하여 주시기 바랍니다.',
        pluginServiceNewVersion : '누끼툴 새버전이 있습니다.',
        pluginServiceNotInstalled : '플러그인 서비스가 설치되어 있지 않습니다.',
        canNotUndo : '더이상 되돌릴 수 없습니다.',
        canNotRedo : '더이상 재실행 할수 없습니다.',

        layerRemoveDone : '레이어 삭제 완료',
        layerEmpty : '선택된 레이어가 없습니다.',
        layerCopyDone : '레이어 복사 완료',
        layerMaximumHoist : '더 이상 올릴수 없습니다.',
        layerMinimumHoist : '더 이상 내릴수 없습니다.',
        layerAdded : '[{{mode}}] 레이어 추가',
        layerAddedText : '[{{mode}}] 레이어 추가 되었습니다',
        fileSizeBig : '허용된 파일 사이즈를 초과하였습니다',
        fileTypeNotAllow : '허용된 파일 타입이 아닙니다-[{{fileType}}]',
        fileUploadDone : '파일 업로드 완료',
        fileUploadFail : '파일 업로드 실패',
        fileTypeAccept : '파일만 업로드 가능합니다',
        imageUploadLayerChange : '[{{index}}]레이어 이미지 변경',
        fontListRequestFail : '폰트 스타일 요청 실패',
        imageAddDone : '이미지 추가 성공',
        imageAddOpen : '이미지 오픈 성공.',
        imageUploadFailByPaste : '[붙여넣기]이미지 업로드 실패',
        imageCropModeFail : '이미지 크롭 불가-도메인이 다릅니다.',
        imageLoadDone : '이미지 로드 완료',
        imageDelDone : '이미지 삭제 완료',
        imageLoadFail : '이미지 로드 실패',
        imageDropFromWindow : '외부 이미지 드롭 시작 - 신규 레이어로 추가됩니다.',
        imageTotalLoad : '전체 이미지 로드 중',
        imageTypeNotSupport : '지원되지 않는 이미지 타입입니다.',
        canvasDrawing : 'CANVAS 이미지 그리는 중',
        textRenderAll : '전체렌더',
        textEmpty : '텍스트가 비어있습니다.',
        textRendering : '텍스트 렌더 진행 중입니다.',
        textRenderRequest : '텍스트 렌더 요청',
        textRenderSuccess : '텍스트 렌더 성공',
        textRenderFail : '텍스트 렌더 실패',
        textRenderError : '텍스트 렌더 에러 발생',
        textLayerCannotChange : 'TEXT 레이어를 변경 할 수 없습니다.',
        renderError : '렌더 실패',
        psdRenderProgress : 'PSD 렌더링 중. 자동 새로고침 활성화 중입니다.',
        warningShowFont : '선택된 폰트와 다르게 보여질 수 있습니다.',
        warningEmptySideLayer : '선택된 영역이 없습니다.',
        warningParameterMissing : '[사용불가]필수 파라미터가 없습니다.',
        warningBlockInfoMissing : '[사용불가]블럭 데이터가 없습니다.',
        checkAddedLayerStatus : '[실패]추가된 이미지 혹은 텍스트 레이어를 확인해주세요.',
        imageCancelCropMode : '[실패]크롭모드를 취소해주세요',
        tagEmpty : '[실패]태그가 없습니다.',
        tagEmpty2 : '선택된 태그가 없습니다.',
        tagLimitExceed : '[실패]태그 길이를 초과하였습니다.',
        tagLimit200 : 'Exceed length 200.',
        tagDuplicated : '중복된 태그',
        tagSearchFail : '태그 이미지 검색 결과가 없습니다.',
        tagMappingWeightSuccess : '[{{tag}}]가중치 변경 완료 -> [{{weight}}]',
        tagMappingWeightFail : '가중치 변경 실패',
        rulerHideAllToggle : '모두 숨기기/보여주기',
        rulerToggle : '룰러 숨기기/보여주기',
        guideToggle : '가이드 숨기기/보여주기',
        guideRemove : '가이드 삭제',
        guideRockToggle : '가이드 잠금/해제',
    },
    EN : {
        LOGOUT : "LOGOUT",
        apply : "Apply",
        langKO : 'KO',
        langEN : 'EN',
        langCN : 'CN',
        langJP : 'JP',
        "전체" : 'ALL',
        "촬영" : 'photograph',
        "일반" : 'normal',
        "반영" : 'Apply',
        "요청" : 'request',
        "모델컷" : 'Model Pic',
        "상품컷" : 'Product Pic',
        "배너" : 'Banner',
        "기타" : 'etc',
        "배경" : "Background",
        "테두리" : "Border",
        totalCnt : 'Total {{cnt}}',
        "테두리굵기" : "Border thickness",
        "자동객체조합" : 'Auto Tag Mapping',
        "인물컷 - 전신 이미지" : "People Pic - Body Image",
        "상품컷 + 인물컷 - 전신" : "Product + People Pic - Body",
        "인물컷 - 상의 이미지" : "People Pic - Top Image",
        "상품컷 + 인물컷- 상의" : "People Pic - Top",
        "취소" : "Cancel",
        "자동조합" : 'Auto Mapping',
        searching : 'Searching',
        saving : 'Saving',
        saveFail : 'Fail saving',
        progressing : 'Progressing',
        askConfirm : 'Ask confirm',
        doneConfirm : 'Done confirm',
        cancelConfirm : 'Cancel confirm',
        "라운드 코너" : "Round Corner",
        "PSD 등록" : "PSD UPLOAD",
        "요청항목" : "REQUEST ITEM",
        "PSD 업로드" : "PSD UPLOAD",
        "업로드 진행중.." : "Uploading..",
        "파일찾기" : "File search",
        "미요청" : "NOT REQUEST",
        "대기" : "WAITING",
        "완료" : "COMPLETED",
        initComplete : "Initialization Complete",
        initError : 'Initialization Fail',
        textRenderAll : 'Render',
        magicWand : 'Magic Wand',
        htmlCoordinates : 'Size &amp; Coordinates',
        htmlTransparency : 'Transparency(unvisible-visible)',
        colorTransparency : 'Color &amp; Transparency',
        htmlOriginalSize : 'Original Size',
        htmlMaskSize : 'Mask Size',
        htmlImageCrop : 'Image Crop',
        htmlDegree : 'Degree',
        htmlImageSizeManagement : 'Image Management',
        htmlStyle : 'Style',
        htmlRequestRender : 'Request Render',
        htmlChooseShop : 'Shops',
        htmlSearchCondition : 'Condition',
        tagInputPlz : 'Input tag please',
        inputProductCode : 'Product Code Missing',
        searchResultEmpty : 'Search Result Empty.',
        autoMagicWandDone : 'Complete auto magic wand.',
        servicePluginTimeoutError : 'Service plugin open error - Please re-open.',
        servicePluginInstall : 'Magic wand tool is not installed.',
        servicePluginInstall2 : 'Please Download and install.',
        pluginServiceNewVersion : 'Plugin Service has new service version.',
        pluginServiceNotInstalled : 'Plugin Service not installed.',
        canNotUndo : 'Can`t Undo anymore.',
        canNotRedo : 'Can`t Redo anymore.',

        layerRemoveDone : 'Layer remove complete',
        layerEmpty : 'Select layer please.',
        layerCopyDone : 'Layer copy done.',
        layerMaximumHoist : 'No longer hoist.',
        layerMinimumHoist : 'No longer lowered.',
        layerAdded : '[{{mode}}] Layer Added.',
        layerAddedText : '[{{mode}}] Layer Added.',
        fileSizeBig : 'Over limited file size.',
        fileTypeNotAllow : 'Not Allowed file type-[{{fileType}}]',
        fileUploadDone : 'File upload done.',
        fileUploadFail : 'File upload fail',
        fileTypeAccept : ' file only acceptable.',
        fontListRequestFail : 'Font style request fail.',
        imageUploadLayerChange : '[{{index}}]Layer image changed.',
        imageAddDone : 'Success image adding.',
        imageAddOpen : 'Success image open.',
        imageUploadFailByPaste : 'Image upload fail.',
        imageCropModeFail : 'Image Crop mode fail - Domain problem.',
        imageLoadDone : 'Complete Image load.',
        imageDelDone : 'Complete Image delete.',
        imageLoadFail : 'Fail Image load.',
        imageDropFromWindow : 'Starting external image : Adding to New Layer.',
        imageTotalLoad : 'Loading Total images.',
        imageTypeNotSupport : 'Not supported Type.',
        canvasDrawing : 'Drawing canvas image.',
        textEmpty : 'Text empty.',
        textRendering : 'Already render requested.',
        textRenderRequest : 'Request text render.',
        textRenderSuccess : 'Text Render success.',
        textRenderFail : 'Text Render fail.',
        textRenderError : 'Text Render Error.',
        textLayerCannotChange : 'Can`t change Text Layer.',
        renderError : 'Render Fail',
        psdRenderProgress : 'PSD render progressing. Auto refresh activated!',
        warningShowFont : 'Result will not exactly same.',
        warningEmptySideLayer : 'Empty selected layer',
        warningParameterMissing : '[DISABLE]Missing essential parameters.',
        warningBlockInfoMissing : '[DISABLE]Missing block information.',
        checkAddedLayerStatus : '[FAIL]Check added Layer status.',
        imageCancelCropMode : '[FAIL]Cancel Image Crop mode',
        tagEmpty : '[FAIL]Tag Empty',
        tagEmpty2 : 'There is no selected tag.',
        tagLimitExceed : '[FAIL]Exceed tag length limit.',
        tagLimit200 : 'Exceed length 200.',
        tagDuplicated : 'Duplicated Tag.',
        tagSearchFail : 'Empty Tag image result',
        tagMappingWeightSuccess : '[{{tag}}]Weight change done -> [{{weight}}]',
        tagMappingWeightFail : 'Weight change fail',
        rulerHideAllToggle : 'HIDE ALL SHOW/HIDE',
        rulerToggle : 'RULER SHOW/HIDE',
        guideToggle : 'GUIDE SHOW/HIDE',
        guideRemove : 'GUIDE DELETE',
        guideRockToggle : 'GUIDE LOCK/UNLOCK',
    }
};

